spring:
  web:
    resources:
      add-mappings: true
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/movy
    username: movy_user
    password: movy_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    outOfOrder: true
    locations: classpath:db.migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

rabbitmq:
  host: localhost
  port: 5672
