version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: movy_postgres
    restart: always
    environment:
      POSTGRES_USER: movy_user
      POSTGRES_PASSWORD: movy_pass
      POSTGRES_DB: movy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: movy_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movy_app
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=production
    ports:
      - "8080:8080"
    networks:
      - movy_net

volumes:
  pgdata:

networks:
  movy_net:
